# Generated by Django 4.1.6 on 2023-02-06 15:11

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='process',
            field=models.CharField(blank=True, choices=[('task', 'task'), ('sub task', 'sub task')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='update_date_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='priority',
            field=models.CharField(blank=True, choices=[('very high', 'very high'), ('high', 'high'), ('medium', 'medium'), ('low', 'low'), ('very low', 'very low')], default='3', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='user',
            field=models.ForeignKey(blank=True, default=django.contrib.auth.models.User, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('condition', models.CharField(blank=True, choices=[('do', 'do'), ('dont', 'dont')], max_length=10, null=True)),
                ('create_date', models.DateField()),
                ('do_date', models.DateField()),
                ('assigment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
