# Generated by Django 4.1.6 on 2023-02-06 15:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ticket', '0003_alter_ticket_priority_alter_ticket_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='assigment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name=' واگذاری'),
        ),
        migrations.AlterField(
            model_name='process',
            name='condition',
            field=models.CharField(blank=True, choices=[('do', 'do'), ('dont', 'dont')], max_length=10, null=True, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='process',
            name='create_date',
            field=models.DateField(verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='process',
            name='description',
            field=models.TextField(verbose_name='شرح کار'),
        ),
        migrations.AlterField(
            model_name='process',
            name='do_date',
            field=models.DateField(verbose_name='تاریخ  انجام'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='content',
            field=models.TextField(verbose_name='محتوا'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ  و زمان'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='department',
            field=models.CharField(blank=True, choices=[('tec', 'tec'), ('fin', 'fin'), ('rev', 'rev')], max_length=10, null=True, verbose_name='دپارتمان'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='priority',
            field=models.CharField(blank=True, choices=[('very high', 'very high'), ('high', 'high'), ('medium', 'medium'), ('low', 'low'), ('very low', 'very low')], default='medium', max_length=10, null=True, verbose_name='اولویت'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='process',
            field=models.CharField(blank=True, choices=[('task', 'task'), ('sub task', 'sub task')], max_length=10, null=True, verbose_name='ثبت روند'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(blank=True, choices=[('open', 'open'), ('close', 'close'), ('ending', 'ending')], default='open', max_length=10, null=True, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='update_date_time',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ و زمان ویرایش'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
    ]
